In [1]:
#Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#Load and read file
clinic = pd.read_csv("messy_clinic_appointments.csv")
clinic.head(20)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1080,Tammy Williams,76,female,2026/02/26,2024/12/03,Christopher Graham,Cardiology,£425.8,1
1,1074,Megan Strickland,69,F,05/23/2025,12-Jun-2024,Brandon Lewis,Orthopedics,€344.26,Y
2,1067,Amanda Schroeder,79,M,30-Nov-2025,"August 05, 24",Deanna Edwards,Neurology,€203.34,Y
3,1072,Anthony Mcpherson,47,F,"May 18, 25",09/09/2024,Karen Parsons,General,Rs85.76,No
4,1092,Benjamin Brown,45,NaN,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,1
5,1057,Joe Sharp,78,1,"September 26, 25",08/31/2025,Kimberly Fields,General,NaN,Yes
6,1018,Alexander Harris,22,Female,30-Oct-2025,12/29/2024,Jim Jones,Cardiology,€99.0,No
7,1074,Raymond Williams,57,M,2025/04/23,28-Mar-2025,James Brooks,Neurology,Rs374.63,No
8,1041,Dustin Willis,54,female,"August 22, 25",2024/11/07,Jamie Hill,General,$452.37,Yes
9,1011,Tina Gallagher,45,M,03/16/2026,12-Dec-2025,Tiffany Gates MD,Neurology,€494.97,Yes
10,1086,Robert Guerrero,54,male,2025/04/24,07-Oct-2024,Shane Brown,Cardiology,£91.91,Y
11,1041,Karen Walker,68,F,2026/03/07,2024/04/24,Natalie White,General,$82.88,Yes
12,1057,Chris Rice,61,1,2025/07/31,"May 05, 24",Amy Olson,Neurology,Rs277.14,N
13,1022,Michael Mack,70,M,"September 21, 25",06-Nov-2024,John Larsen II,Orthopedics,€411.01,Y
14,1046,Andrea Hubbard,36,F,2026/03/12,11/08/2025,Andrea Gates,Cardiology,£67.51,N
15,1025,Brian Jones,23,female,06-Feb-2026,2025/03/09,Robert Navarro,Orthopedics,€163.99,Y
16,1027,Kelly Olsen,72,Male,"August 27, 25",13-Feb-2025,Christopher Bryant,Cardiology,£252.38,Yes
17,1059,Andrew Oconnor,66,Female,"November 11, 25",01-Dec-2024,Christina Hill,Cardiology,$153.07,Y
18,1086,Dennis Hurley,81,M,04/10/2025,2024/12/16,Daniel Jacobson,General,Rs329.3,1
19,1033,Paul Brock,76,Female,2025/11/05,2025/05/23,Kayla Savage,Neurology,€135.45,Yes

In [3]:
#Create a copy of the dataset
clinic_copy = clinic.copy()

In [4]:
#Dataset information
clinic.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          1000 non-null   int64
 1   patient_name        1000 non-null   str
 2   age                 1000 non-null   int64
 3   gender              950 non-null    str
 4   appointment_date    1000 non-null   str
 5   booking_date        1000 non-null   str
 6   doctor              1000 non-null   str
 7   department          1000 non-null   str
 8   billing_amount      950 non-null    str
 9   follow_up_required  1000 non-null   str
dtypes: int64(2), str(8)
memory usage: 146.4 KB

In [5]:
#Check for duplicates
clinic[clinic.duplicated()]

Empty DataFrame
Columns: [patient_id, patient_name, age, gender, appointment_date, booking_date, doctor, department, billing_amount, follow_up_required]
Index: []

In [6]:
#Statistic information of the dataset
clinic.describe(include='all')

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
count,1000.000000,1000,1000.000000,950,1000,1000,1000,1000,950,1000
unique,NaN,988,NaN,8,735,822,990,4,949,6
top,NaN,Regina Wilson,NaN,0,2026/02/11,"August 05, 24",Jennifer Adams,Neurology,€243.78,0
freq,NaN,2,NaN,129,4,3,2,273,2,185
mean,1050.521000,NaN,53.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,28.888581,NaN,21.137604,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1000.000000,NaN,18.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1025.000000,NaN,34.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1051.000000,NaN,55.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1075.000000,NaN,71.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1100.000000,NaN,90.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#Check corresponding missing rows of a column
clinic[clinic["gender"].isna()]

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
4,1092,Benjamin Brown,45,NaN,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,1
36,1003,Katelyn Smith,19,NaN,"October 16, 25",09/21/2025,Robert Henry,Neurology,$481.44,0
43,1063,Edward Sanders,29,NaN,2025/09/16,"April 29, 25",Steven Bailey,Orthopedics,Rs479.77,0
64,1077,Jennifer Stark,34,NaN,06/29/2025,04-Dec-2024,Jason Williams,Neurology,Rs270.33,N
70,1095,Jessica Heath,86,NaN,2025/06/25,04/24/2024,Sherri Long,Cardiology,€61.37,Yes
84,1093,Craig Nixon,55,NaN,2025/10/12,08/20/2025,William Key,Neurology,£341.19,No
91,1040,Chelsea Burns,62,NaN,"December 29, 25",13-May-2024,Michael Morales,Cardiology,Rs193.6,Yes
102,1088,Sarah Hahn,60,NaN,19-Mar-2026,2024/10/18,Theresa Lee,General,Rs123.03,Yes
108,1018,Monica Horton,53,NaN,11-Oct-2025,"March 30, 24",Kayla Stein,Neurology,$277.21,Yes
125,1053,John Johnson,81,NaN,23-Apr-2025,2024/12/30,Steve Bush,General,$162.94,N
164,1082,Gary Walker,87,NaN,"March 26, 25",26-Mar-2024,Matthew Lopez,Orthopedics,Rs216.23,Yes
173,1084,Troy Taylor,52,NaN,"December 28, 25",24-Feb-2025,Jason Gill,General,£464.69,Yes
208,1048,Walter Webb,33,NaN,2025/09/26,"September 03, 24",Dale Herrera,Neurology,NaN,Y
222,1060,Stephanie Bryant,32,NaN,2026/01/02,2025/02/18,Sara Booth,Orthopedics,£452.69,Yes
244,1015,Stephen Hicks,88,NaN,10/19/2025,06/05/2025,Christopher Underwood,Orthopedics,£266.53,1
248,1093,Whitney Bradley,31,NaN,27-May-2025,20-Dec-2024,Ryan White,General,€111.71,0
255,1097,Megan Murphy,35,NaN,19-Apr-2025,2025/04/11,Kevin Coleman,Cardiology,Rs359.5,N
267,1034,Lisa Fisher,44,NaN,16-Jul-2025,06/12/2025,Karen Martin,Neurology,$417.38,Yes
294,1004,Phillip Blevins,64,NaN,03/12/2026,"June 04, 24",Darryl Garcia,General,$124.85,1
324,1010,Steven Baldwin,87,NaN,05-Jun-2025,04/14/2024,Lori Reid,Neurology,Rs496.78,1
345,1014,Jennifer Schwartz,90,NaN,"February 12, 26",08/14/2024,Mrs. Michelle Ramsey,Orthopedics,€474.34,N
364,1050,Logan Gonzalez,81,NaN,2026/02/17,2025/04/03,John Anderson,Neurology,€209.27,Y
365,1019,Brittney Gonzales,38,NaN,12/20/2025,14-Aug-2025,Kimberly Caldwell,Orthopedics,Rs347.87,1
379,1088,Mary Werner,32,NaN,07/22/2025,2024/04/12,Bonnie Walker,Orthopedics,$69.13,Yes
392,1021,Ashley Martinez,68,NaN,05/07/2025,10/18/2024,Spencer Torres,Orthopedics,$296.8,N
400,1067,Karla Bush,66,NaN,"May 23, 25",08/14/2024,Victor Hernandez,Cardiology,Rs135.85,Y
441,1058,Kimberly Lee,88,NaN,2025/10/19,"November 16, 24",Vanessa Ramirez,Neurology,£438.81,N
533,1049,Kimberly Hill,37,NaN,05/10/2025,2024/08/26,Kenneth Long,Neurology,Rs194.81,0
542,1024,Alejandra Perkins,72,NaN,"August 03, 25",2025/04/11,Daniel Dickerson,Orthopedics,NaN,Y
583,1015,Nichole Anderson,87,NaN,10-May-2025,"February 06, 25",Richard Vega,Cardiology,£316.89,Yes
617,1073,Carrie Davis,50,NaN,2026/01/19,2024/04/01,Michael Jones,Neurology,Rs390.86,0
618,1016,Pamela Young,40,NaN,"May 30, 25",05/23/2025,Yvonne Richardson,Orthopedics,$136.23,1
632,1097,Kathryn Green,86,NaN,2025/05/01,"August 19, 24",Robert Moreno,Cardiology,Rs415.78,Yes
676,1004,Samuel Harrison,53,NaN,"August 09, 25",07/06/2024,Hunter Powell,Neurology,Rs492.92,Yes
681,1014,Bradley Jones,61,NaN,07/14/2025,22-Dec-2024,Douglas Patton,Cardiology,Rs257.41,1
700,1098,Jennifer Dorsey,27,NaN,02/10/2026,06/29/2025,Michael Stanley,General,$147.08,N
704,1015,Veronica Shaw,86,NaN,"September 22, 25","July 15, 24",Michael Franco,Orthopedics,£174.42,Yes
714,1024,Tristan Booth,22,NaN,07/10/2025,07/16/2024,Alicia Hall,Neurology,$477.72,0
729,1068,Regina Smith,87,NaN,2025/08/30,"December 15, 24",Donna Orr,General,$246.13,N
742,1073,Molly Hayden,75,NaN,"January 06, 26",22-Feb-2025,Brian Chambers,General,£306.62,N
814,1074,Gary Taylor,87,NaN,"May 19, 25",2024/06/12,Lauren Medina,General,£321.5,Y
820,1056,Brian Patel,33,NaN,"October 16, 25",13-Sep-2024,Tracy Harris,Orthopedics,€124.69,No
821,1008,George Houston,71,NaN,06-Sep-2025,2024/05/21,Brian Vincent,Neurology,€129.38,0
837,1025,Adrian Vincent,42,NaN,21-Sep-2025,05-Dec-2024,William Coleman MD,Orthopedics,£352.01,No
871,1056,Jean Kramer,30,NaN,05/29/2025,"May 31, 24",Donald Clark,Orthopedics,€441.92,Yes
881,1013,Robert Humphrey,24,NaN,"April 10, 25",03/22/2025,Vanessa Brown,Orthopedics,$281.71,No
885,1040,Laura Ford,36,NaN,27-May-2025,2024/12/02,Kyle Evans,Orthopedics,£186.51,No
889,1070,Stacy Gardner,53,NaN,01/18/2026,"March 11, 25",Michael Campbell,Neurology,£74.78,Yes
917,1094,Joshua Wallace,60,NaN,12/26/2025,22-May-2024,Melissa Price,General,€416.08,0
984,1081,Courtney Wright,43,NaN,26-Jul-2025,"May 24, 24",Daniel Morris,Orthopedics,Rs362.65,1

In [8]:
#Check corresponding missing rows in the whole dataset
clinic[clinic.isnull().any(axis=1)]

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
4,1092,Benjamin Brown,45,NaN,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,1
5,1057,Joe Sharp,78,1,"September 26, 25",08/31/2025,Kimberly Fields,General,NaN,Yes
33,1041,Nicole Shaw,20,male,05/07/2025,01/19/2025,Mr. Brian Morton,Neurology,NaN,Y
36,1003,Katelyn Smith,19,NaN,"October 16, 25",09/21/2025,Robert Henry,Neurology,$481.44,0
43,1063,Edward Sanders,29,NaN,2025/09/16,"April 29, 25",Steven Bailey,Orthopedics,Rs479.77,0
...,...,...,...,...,...,...,...,...,...,...
933,1034,Amanda Douglas,90,1,03/07/2026,2024/06/25,Gregory Gonzalez,General,NaN,0
937,1048,Ashley Black,84,F,05/29/2025,29-Jan-2025,Dennis Murphy,Neurology,NaN,N
938,1068,Wendy Parks,40,male,2026/02/14,09-Sep-2025,Melissa Williams,Neurology,NaN,1
956,1016,Jocelyn Strickland,22,M,30-Apr-2025,"July 10, 24",Vincent Kemp,Cardiology,NaN,N
984,1081,Courtney Wright,43,NaN,26-Jul-2025,"May 24, 24",Daniel Morris,Orthopedics,Rs362.65,1

In [9]:
#Remove the missing rows from the dataset
clinic.dropna(inplace=True)

In [10]:
#Cross-checking the dataset information for verification
clinic.info()

<class 'pandas.DataFrame'>
Index: 902 entries, 0 to 999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          902 non-null    int64
 1   patient_name        902 non-null    str
 2   age                 902 non-null    int64
 3   gender              902 non-null    str
 4   appointment_date    902 non-null    str
 5   booking_date        902 non-null    str
 6   doctor              902 non-null    str
 7   department          902 non-null    str
 8   billing_amount      902 non-null    str
 9   follow_up_required  902 non-null    str
dtypes: int64(2), str(8)
memory usage: 140.1 KB

In [11]:
#Rename the follow_up_required column
clinic = clinic.rename(columns= {"follow_up_required":"follow_up"})

In [12]:
#Capitalize the column heads
clinic.columns = clinic.columns.str.replace("_"," ").str.title()

In [13]:
#Rename the patient id column
clinic = clinic.rename(columns= {"Patient Id":"Patient ID"})

In [14]:
#Better view of values under gender column
clinic["Gender"].unique()

<ArrowStringArray>
['female', 'F', 'M', 'Female', 'male', '1', 'Male', '0']
Length: 8, dtype: str

In [15]:
#Changing the gender values to male or female
clinic["Gender"] = clinic["Gender"].replace(["F","Female","0"],"female").replace(["M","Male","1"],"male")

In [16]:
#Better view of values under follow up column
clinic["Follow Up"].unique()

<ArrowStringArray>
['1', 'Y', 'No', 'Yes', 'N', '0']
Length: 6, dtype: str

In [17]:
#View of the dataset to determine which class 0/1 belongs
clinic.sample(20) #Done 3x

,Patient ID,Patient Name,Age,Gender,Appointment Date,Booking Date,Doctor,Department,Billing Amount,Follow Up
734,1044,Nicole Warren,63,female,19-Sep-2025,"February 07, 25",Kimberly Beck,General,£415.35,N
93,1070,Jared Green,28,female,"October 08, 25",10-May-2025,Brenda Castro,Neurology,€235.69,No
716,1024,Alexander Vega,35,male,"August 17, 25",08/06/2025,Karen Gomez,Neurology,$270.15,1
473,1067,Jessica Wilson,72,female,03/20/2026,13-Jul-2024,Sharon Nash,Orthopedics,€437.18,N
656,1043,Derek Smith,82,female,23-May-2025,2024/10/18,Jeremy Burton,Cardiology,$215.76,N
996,1008,Jack Cooper,67,female,"April 09, 25","June 20, 24",Christopher Smith,General,Rs244.49,No
394,1005,Mr. Phillip Baxter,80,male,07/24/2025,01/16/2025,Tricia Hunt,General,$320.72,N
874,1078,James Gibbs,25,female,"November 16, 25",09/22/2024,Lisa Norris,Cardiology,$368.56,No
32,1094,Stacy Cunningham,32,male,"March 09, 26",2024/11/14,Laura Klein,General,£413.53,0
540,1086,Bryan Fritz,86,female,2025/08/03,02/19/2025,Kelsey Hernandez,Orthopedics,$338.43,Y
424,1077,Julia Mckenzie,30,male,2025/08/13,02/10/2025,Sarah Scott,Cardiology,€91.94,1
404,1013,Rachel Carlson,27,female,"January 05, 26",2024/12/12,Paul Martinez,Neurology,$379.39,Y
961,1074,Eugene Underwood,80,male,2025/11/11,"May 20, 25",Benjamin Williams,Neurology,Rs467.55,No
530,1091,Tiffany Miller,85,male,2025/03/29,2025/03/07,Melissa Bradley,Cardiology,€151.02,No
783,1045,Michael Evans,65,male,"March 28, 25","January 04, 25",Manuel Vargas,Orthopedics,€304.67,No
505,1082,Tyler Trujillo,72,male,2025/12/11,"January 24, 25",Andrea Walsh,Cardiology,£167.07,No
306,1011,Allison Mcgrath,60,male,06/22/2025,2024/04/26,Morgan Mccoy,Cardiology,Rs125.6,0
28,1002,Cassandra Gardner,42,male,"October 14, 25",2024/11/04,Gregory Kirk,Neurology,Rs342.38,0
105,1027,Benjamin Hughes,32,female,2026/03/02,17-Dec-2025,Nicholas Mcneil,Cardiology,£125.31,1
500,1040,Benjamin Allen,20,female,"November 22, 25",04/06/2025,Richard Johnson,Cardiology,€257.17,No

In [18]:
#Change follow_up column values to yes or no
clinic["Follow Up"] = clinic["Follow Up"].replace(["1","Y","Yes"],"yes").replace(["0","N","No"],"no")

In [19]:
#Convert the booking and appointment date to datetime data type
clinic["Appointment Date"] = pd.to_datetime(clinic["Appointment Date"], format="mixed")
clinic["Booking Date"] = pd.to_datetime(clinic["Booking Date"], format="mixed")

In [20]:
#Create a new column for the billing amount that converts all currencies to the euros currency.
rates = {"GBP":1.1667,
         "USD": 0.8580,
         "INR": 0.0090,
         "EUR": 1.0000} #Define exchange rate

clinic["Billing Amount"] = clinic["Billing Amount"].str.strip() #Remove unnecessary space from the beginning and end

clinic["Currency"] = np.select([clinic["Billing Amount"].str.startswith("£"),
                                clinic["Billing Amount"].str.startswith("$"),
                                 clinic["Billing Amount"].str.startswith("Rs"),
                                  clinic["Billing Amount"].str.startswith("€")],["GBP","USD","INR","EUR"], default=pd.NA) #Create a currency column

clinic["Amount"] = clinic["Billing Amount"].str.replace(r"£|€|\$|Rs","",regex=True).str.strip() #Remove the currency symbol and create a new column

clinic["Amount"] = pd.to_numeric(clinic["Amount"], errors="coerce") #Convert to numeric data type

clinic["Amount Charge(€)"] = (clinic["Amount"] * clinic["Currency"].map(rates)).round(2) #Create a column that has the right conversion

In [21]:
#View of the dataset
clinic.sample(10)

     Patient ID        Patient Name  Age  Gender Appointment Date  \
658        1086  Richard Richardson   80  female       2025-11-24
508        1041       Troy Marshall   67  female       2025-04-17
906        1006   Christina Spencer   61    male       2025-11-14
568        1048      Victoria Young   47  female       2025-08-06
612        1008   Jacqueline Howell   30    male       2026-02-21
167        1035       Michael Glenn   60    male       2025-11-13
189        1068         Judy Nguyen   29    male       2025-05-27
915        1066        Daniel White   37  female       2025-05-25
531        1003      Cassandra Cain   64  female       2026-01-24
427        1081      Brandy Navarro   27  female       2025-07-16

    Booking Date             Doctor   Department Billing Amount Follow Up  \
658   2024-12-29       Robin Hebert   Cardiology       Rs226.12       yes
508   2024-09-15  Benjamin Robinson  Orthopedics        $478.18        no
906   2024-05-10        Mark Kelley  Orthopedics        £308.28        no
568   2025-07-21    Lauren Whitaker    Neurology        $174.04       yes
612   2025-05-23      Felicia Smith   Cardiology        £316.64       yes
167   2025-06-23    Robert Martinez   Cardiology         $99.19        no
189   2024-10-23    Michelle Ortega      General        $429.14       yes
915   2024-10-12        Justin Hall      General        €470.63       yes
531   2025-02-08   Jessica Williams   Cardiology        Rs79.59        no
427   2025-06-13    Matthew Nichols  Orthopedics       Rs288.43       yes

    Currency  Amount  Amount Charge(€)
658      INR  226.12              2.04
508      USD  478.18            410.28
906      GBP  308.28            359.67
568      USD  174.04            149.33
612      GBP  316.64            369.42
167      USD   99.19             85.11
189      USD  429.14            368.20
915      EUR  470.63            470.63
531      INR   79.59              0.72
427      INR  288.43              2.60

In [22]:
#Arrange column in a presiding logical order
logical_order = ["Patient ID","Patient Name","Age","Gender","Appointment Date","Booking Date","Doctor","Department","Billing Amount","Currency","Amount","Amount Charge(€)","Follow Up"]

clinic = clinic[logical_order]

In [23]:
#Cross-checking the dataset information for verification
clinic.info()

<class 'pandas.DataFrame'>
Index: 902 entries, 0 to 999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Patient ID        902 non-null    int64
 1   Patient Name      902 non-null    str
 2   Age               902 non-null    int64
 3   Gender            902 non-null    str
 4   Appointment Date  902 non-null    datetime64[us]
 5   Booking Date      902 non-null    datetime64[us]
 6   Doctor            902 non-null    str
 7   Department        902 non-null    str
 8   Billing Amount    902 non-null    str
 9   Currency          902 non-null    str
 10  Amount            902 non-null    float64
 11  Amount Charge(€)  902 non-null    float64
 12  Follow Up         902 non-null    str
dtypes: datetime64[us](2), float64(2), int64(2), str(7)
memory usage: 146.7 KB
None

In [26]:
#Statistical information of the dataset
clinic.describe()

         Patient ID   Patient Name         Age  Gender  \
count    902.000000            902  902.000000     902
unique          NaN            892         NaN       2
top             NaN  Regina Wilson         NaN  female
freq            NaN              2         NaN     460
mean    1050.514412            NaN   53.684035     NaN
min     1000.000000            NaN   18.000000     NaN
25%     1025.250000            NaN   34.250000     NaN
50%     1051.000000            NaN   55.000000     NaN
75%     1075.000000            NaN   71.000000     NaN
max     1100.000000            NaN   90.000000     NaN
std       28.918564            NaN   21.069489     NaN

                  Appointment Date                Booking Date  \
count                          902                         902
unique                         NaN                         NaN
top                            NaN                         NaN
freq                           NaN                         NaN
mean    2025-10-03 03:22:44.966740  2025-01-03 05:43:14.235033
min            2025-03-26 00:00:00         2024-03-26 00:00:00
25%            2025-07-06 00:00:00         2024-08-16 06:00:00
50%            2025-10-12 00:00:00         2024-12-26 00:00:00
75%            2025-12-30 00:00:00         2025-05-13 00:00:00
max            2026-03-26 00:00:00         2026-03-07 00:00:00
std                            NaN                         NaN

                Doctor Department Billing Amount Currency      Amount  \
count              902        902            902      902  902.000000
unique             892          4            901        4         NaN
top     Jennifer Adams  Neurology        €243.78      INR         NaN
freq                 2        245              2      237         NaN
mean               NaN        NaN            NaN      NaN  275.726364
min                NaN        NaN            NaN      NaN   51.380000
25%                NaN        NaN            NaN      NaN  163.100000
50%                NaN        NaN            NaN      NaN  269.140000
75%                NaN        NaN            NaN      NaN  387.707500
max                NaN        NaN            NaN      NaN  499.750000
std                NaN        NaN            NaN      NaN  129.832861

        Amount Charge(€) Follow Up
count         902.000000       902
unique               NaN         2
top                  NaN       yes
freq                 NaN       463
mean          202.680310       NaN
min             0.500000       NaN
25%             4.322500       NaN
50%           189.065000       NaN
75%           342.197500       NaN
max           582.960000       NaN
std           166.739354       NaN

In [ ]:
#Feature Engineering.