In [1]:
#Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#Load and read file
clinic = pd.read_csv("messy_clinic_appointments.csv")
clinic.head(20)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1080,Tammy Williams,76,female,2026/02/26,2024/12/03,Christopher Graham,Cardiology,£425.8,1
1,1074,Megan Strickland,69,F,05/23/2025,12-Jun-2024,Brandon Lewis,Orthopedics,€344.26,Y
2,1067,Amanda Schroeder,79,M,30-Nov-2025,"August 05, 24",Deanna Edwards,Neurology,€203.34,Y
3,1072,Anthony Mcpherson,47,F,"May 18, 25",09/09/2024,Karen Parsons,General,Rs85.76,No
4,1092,Benjamin Brown,45,NaN,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,1

In [3]:
#Create a copy of the dataset
clinic_copy = clinic.copy()

In [40]:
clinic.info()

<class 'pandas.DataFrame'>
Index: 902 entries, 0 to 999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          902 non-null    int64
 1   patient_name        902 non-null    str
 2   age                 902 non-null    int64
 3   gender              902 non-null    str
 4   appointment_date    902 non-null    str
 5   booking_date        902 non-null    str
 6   doctor              902 non-null    str
 7   department          902 non-null    str
 8   billing_amount      902 non-null    str
 9   follow_up_required  902 non-null    str
dtypes: int64(2), str(8)
memory usage: 140.1 KB

In [7]:
clinic[clinic.duplicated()]

Empty DataFrame
Columns: [patient_id, patient_name, age, gender, appointment_date, booking_date, doctor, department, billing_amount, follow_up_required]
Index: []

In [38]:
clinic.describe()

        patient_id         age
count   902.000000  902.000000
mean   1050.514412   53.684035
std      28.918564   21.069489
min    1000.000000   18.000000
25%    1025.250000   34.250000
50%    1051.000000   55.000000
75%    1075.000000   71.000000
max    1100.000000   90.000000

In [29]:
#Check corresponding missing rows of a column
clinic[clinic["gender"].isna()]

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
4,1092,Benjamin Brown,45,NaN,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,1
36,1003,Katelyn Smith,19,NaN,"October 16, 25",09/21/2025,Robert Henry,Neurology,$481.44,0
43,1063,Edward Sanders,29,NaN,2025/09/16,"April 29, 25",Steven Bailey,Orthopedics,Rs479.77,0
64,1077,Jennifer Stark,34,NaN,06/29/2025,04-Dec-2024,Jason Williams,Neurology,Rs270.33,N
70,1095,Jessica Heath,86,NaN,2025/06/25,04/24/2024,Sherri Long,Cardiology,€61.37,Yes
84,1093,Craig Nixon,55,NaN,2025/10/12,08/20/2025,William Key,Neurology,£341.19,No
91,1040,Chelsea Burns,62,NaN,"December 29, 25",13-May-2024,Michael Morales,Cardiology,Rs193.6,Yes
102,1088,Sarah Hahn,60,NaN,19-Mar-2026,2024/10/18,Theresa Lee,General,Rs123.03,Yes
108,1018,Monica Horton,53,NaN,11-Oct-2025,"March 30, 24",Kayla Stein,Neurology,$277.21,Yes
125,1053,John Johnson,81,NaN,23-Apr-2025,2024/12/30,Steve Bush,General,$162.94,N
164,1082,Gary Walker,87,NaN,"March 26, 25",26-Mar-2024,Matthew Lopez,Orthopedics,Rs216.23,Yes
173,1084,Troy Taylor,52,NaN,"December 28, 25",24-Feb-2025,Jason Gill,General,£464.69,Yes
208,1048,Walter Webb,33,NaN,2025/09/26,"September 03, 24",Dale Herrera,Neurology,NaN,Y
222,1060,Stephanie Bryant,32,NaN,2026/01/02,2025/02/18,Sara Booth,Orthopedics,£452.69,Yes
244,1015,Stephen Hicks,88,NaN,10/19/2025,06/05/2025,Christopher Underwood,Orthopedics,£266.53,1
248,1093,Whitney Bradley,31,NaN,27-May-2025,20-Dec-2024,Ryan White,General,€111.71,0
255,1097,Megan Murphy,35,NaN,19-Apr-2025,2025/04/11,Kevin Coleman,Cardiology,Rs359.5,N
267,1034,Lisa Fisher,44,NaN,16-Jul-2025,06/12/2025,Karen Martin,Neurology,$417.38,Yes
294,1004,Phillip Blevins,64,NaN,03/12/2026,"June 04, 24",Darryl Garcia,General,$124.85,1
324,1010,Steven Baldwin,87,NaN,05-Jun-2025,04/14/2024,Lori Reid,Neurology,Rs496.78,1
345,1014,Jennifer Schwartz,90,NaN,"February 12, 26",08/14/2024,Mrs. Michelle Ramsey,Orthopedics,€474.34,N
364,1050,Logan Gonzalez,81,NaN,2026/02/17,2025/04/03,John Anderson,Neurology,€209.27,Y
365,1019,Brittney Gonzales,38,NaN,12/20/2025,14-Aug-2025,Kimberly Caldwell,Orthopedics,Rs347.87,1
379,1088,Mary Werner,32,NaN,07/22/2025,2024/04/12,Bonnie Walker,Orthopedics,$69.13,Yes
392,1021,Ashley Martinez,68,NaN,05/07/2025,10/18/2024,Spencer Torres,Orthopedics,$296.8,N
400,1067,Karla Bush,66,NaN,"May 23, 25",08/14/2024,Victor Hernandez,Cardiology,Rs135.85,Y
441,1058,Kimberly Lee,88,NaN,2025/10/19,"November 16, 24",Vanessa Ramirez,Neurology,£438.81,N
533,1049,Kimberly Hill,37,NaN,05/10/2025,2024/08/26,Kenneth Long,Neurology,Rs194.81,0
542,1024,Alejandra Perkins,72,NaN,"August 03, 25",2025/04/11,Daniel Dickerson,Orthopedics,NaN,Y
583,1015,Nichole Anderson,87,NaN,10-May-2025,"February 06, 25",Richard Vega,Cardiology,£316.89,Yes
617,1073,Carrie Davis,50,NaN,2026/01/19,2024/04/01,Michael Jones,Neurology,Rs390.86,0
618,1016,Pamela Young,40,NaN,"May 30, 25",05/23/2025,Yvonne Richardson,Orthopedics,$136.23,1
632,1097,Kathryn Green,86,NaN,2025/05/01,"August 19, 24",Robert Moreno,Cardiology,Rs415.78,Yes
676,1004,Samuel Harrison,53,NaN,"August 09, 25",07/06/2024,Hunter Powell,Neurology,Rs492.92,Yes
681,1014,Bradley Jones,61,NaN,07/14/2025,22-Dec-2024,Douglas Patton,Cardiology,Rs257.41,1
700,1098,Jennifer Dorsey,27,NaN,02/10/2026,06/29/2025,Michael Stanley,General,$147.08,N
704,1015,Veronica Shaw,86,NaN,"September 22, 25","July 15, 24",Michael Franco,Orthopedics,£174.42,Yes
714,1024,Tristan Booth,22,NaN,07/10/2025,07/16/2024,Alicia Hall,Neurology,$477.72,0
729,1068,Regina Smith,87,NaN,2025/08/30,"December 15, 24",Donna Orr,General,$246.13,N
742,1073,Molly Hayden,75,NaN,"January 06, 26",22-Feb-2025,Brian Chambers,General,£306.62,N
814,1074,Gary Taylor,87,NaN,"May 19, 25",2024/06/12,Lauren Medina,General,£321.5,Y
820,1056,Brian Patel,33,NaN,"October 16, 25",13-Sep-2024,Tracy Harris,Orthopedics,€124.69,No
821,1008,George Houston,71,NaN,06-Sep-2025,2024/05/21,Brian Vincent,Neurology,€129.38,0
837,1025,Adrian Vincent,42,NaN,21-Sep-2025,05-Dec-2024,William Coleman MD,Orthopedics,£352.01,No
871,1056,Jean Kramer,30,NaN,05/29/2025,"May 31, 24",Donald Clark,Orthopedics,€441.92,Yes
881,1013,Robert Humphrey,24,NaN,"April 10, 25",03/22/2025,Vanessa Brown,Orthopedics,$281.71,No
885,1040,Laura Ford,36,NaN,27-May-2025,2024/12/02,Kyle Evans,Orthopedics,£186.51,No
889,1070,Stacy Gardner,53,NaN,01/18/2026,"March 11, 25",Michael Campbell,Neurology,£74.78,Yes
917,1094,Joshua Wallace,60,NaN,12/26/2025,22-May-2024,Melissa Price,General,€416.08,0
984,1081,Courtney Wright,43,NaN,26-Jul-2025,"May 24, 24",Daniel Morris,Orthopedics,Rs362.65,1

In [32]:
#Check corresponding missing rows in the whole dataset
clinic[clinic.isnull().any(axis=1)]

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
4,1092,Benjamin Brown,45,NaN,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,1
5,1057,Joe Sharp,78,1,"September 26, 25",08/31/2025,Kimberly Fields,General,NaN,Yes
33,1041,Nicole Shaw,20,male,05/07/2025,01/19/2025,Mr. Brian Morton,Neurology,NaN,Y
36,1003,Katelyn Smith,19,NaN,"October 16, 25",09/21/2025,Robert Henry,Neurology,$481.44,0
43,1063,Edward Sanders,29,NaN,2025/09/16,"April 29, 25",Steven Bailey,Orthopedics,Rs479.77,0
...,...,...,...,...,...,...,...,...,...,...
933,1034,Amanda Douglas,90,1,03/07/2026,2024/06/25,Gregory Gonzalez,General,NaN,0
937,1048,Ashley Black,84,F,05/29/2025,29-Jan-2025,Dennis Murphy,Neurology,NaN,N
938,1068,Wendy Parks,40,male,2026/02/14,09-Sep-2025,Melissa Williams,Neurology,NaN,1
956,1016,Jocelyn Strickland,22,M,30-Apr-2025,"July 10, 24",Vincent Kemp,Cardiology,NaN,N
984,1081,Courtney Wright,43,NaN,26-Jul-2025,"May 24, 24",Daniel Morris,Orthopedics,Rs362.65,1

In [35]:
clinic.dropna(inplace=True)

In [36]:
clinic.info()

<class 'pandas.DataFrame'>
Index: 902 entries, 0 to 999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          902 non-null    int64
 1   patient_name        902 non-null    str
 2   age                 902 non-null    int64
 3   gender              902 non-null    str
 4   appointment_date    902 non-null    str
 5   booking_date        902 non-null    str
 6   doctor              902 non-null    str
 7   department          902 non-null    str
 8   billing_amount      902 non-null    str
 9   follow_up_required  902 non-null    str
dtypes: int64(2), str(8)
memory usage: 140.1 KB